version: '3.8'
services:
  neocharge:
    image: 583333730249.dkr.ecr.us-west-1.amazonaws.com/neo-be-dev:b31931665a01347a77c6fe3539a0b3ff75ac1f03
    ports:
      - '8080:8080'
    environment:
      API_KEY: ${API_KEY}
      ARCADIA_APP_ID: ${ARCADIA_APP_ID}
      ARCADIA_APP_KEY: ${ARCADIA_APP_KEY}
      ARCADIA_APP_URL: ${ARCADIA_APP_URL}
      DD_API_KEY: ${DD_API_KEY}
      ENODE_API: ${ENODE_API}
      ENODE_CLIENT_ID: ${ENODE_CLIENT_ID}
      ENODE_CLIENT_SECRET: ${ENODE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
      KAFKA_SASL_MECHANISMS: ${KAFKA_SASL_MECHANISMS}
      KAFKA_SASL_PASSWORD: ${KAFKA_SASL_PASSWORD}
      KAFKA_SASL_USERNAME: ${KAFKA_SASL_USERNAME}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      LEAP_ACCOUNT_ID: ${LEAP_ACCOUNT_ID}
      LEAP_API_HOST: ${LEAP_API_HOST}
      LEAP_API_KEY: ${LEAP_API_KEY}
      LEAP_ONBOARDING_HOST: ${LEAP_ONBOARDING_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_POOL_MAX: ${MYSQL_POOL_MAX}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      OPENEI_APP_KEY: ${OPENEI_APP_KEY}
      OPENEI_APP_URL: ${OPENEI_APP_URL}
      LEAP_ONBOARDING_ENV: ${LEAP_ONBOARDING_ENV}
      LEAP_ONBOARDING_UTILITIES: ${LEAP_ONBOARDING_UTILITIES}
      LEAP_WEBHOOK_URL: ${LEAP_WEBHOOK_URL}
      LEAP_METER_SYNC_PERIOD: ${LEAP_METER_SYNC_PERIOD}
      ENODE_AUTH_TOKEN_API: ${ENODE_AUTH_TOKEN_API}
      LEAP_BASE_URL: ${LEAP_BASE_URL}
      STATSD_HOST_IP: ${STATSD_HOST_IP}
      LOG_LEVEL: ${LOG_LEVEL}
      HTTP_PORT: ${HTTP_PORT}

